name: Zach Seifts's blog
markdown: kramdown
exclude: [Gemfile, Gemfile.lock]

# Pagination
paginate: 3
paginate_path: "/posts/:num"

sass:
  style: compressed

# Load extra gems
gems:
  - jekyll-seo-tag
  - jekyll-sitemap

# Jekyll SEO config
title: Zach Seifts

# Social things
default_author: Zach Seifts
github: zachseifts
untappd: notzach
