name: Zach Seifts's blog
markdown: kramdown
exclude: [Gemfile, Gemfile.lock]

# Pagination
paginate: 3
paginate_path: "/posts/:num"

sass:
  style: compressed

# Load extra gems
gems:
  - jekyll-seo-tag
  - jekyll-sitemap

# Jekyll SEO config
title: Zach Seifts

# Social things
default_author: Zach Seifts
post_description: This is a short description about the author of this post. It's full of works and other characters that should display on any post by this author.
github: zachseifts
untappd: notzach
