name: My blog as a github pages thing.
markdown: kramdown
exclude: [Gemfile, Gemfile.lock]

paginate: 3
paginate_path: "/posts/:num"

sass:
  style: compressed

gems:
  - jekyll-seo-tag

# Jekyll SEO config
title: Zach Seifts
author: zach
social:
  name: Zach Seifts

github: zachseifts
untappd: notzach
